name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build gh-pages
        run: |
          cd editor
          npm install

          npm run build
          cp src/404.html dist/editor
          npm run generate:support-info dist/editor/assets/support-info.json
          npm run ci
          cd ../generator
          cargo run snippets ../gta3/snippets > ../editor/dist/editor/assets/gta3/snippets.json
          cargo run snippets ../vc/snippets > ../editor/dist/editor/assets/vc/snippets.json
          cargo run snippets ../sa/snippets > ../editor/dist/editor/assets/sa/snippets.json
          cargo run snippets ../unknown_x86/snippets > ../editor/dist/editor/assets/unknown_x86/snippets.json
          cargo run snippets ../unknown_x64/snippets > ../editor/dist/editor/assets/unknown_x64/snippets.json

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./editor/dist/editor
          cname: library.sannybuilder.com
